repo: "stacked-nav"
canvasCourse: "467502"
canvasAssignment: "4178295"

naming: true
commits: 2

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - "header"
      - "header h1"
      - "header nav"
      - "header nav ul"
      - "header nav ul li a"
    search:
      - "Beetles"
      - "Ant Nest"
      - "Stag"
      - "Dung"
      - "Tortoise"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ["html", "box-sizing", "border-box"]
      - ["body", "margin", "0"]
    search:
      - "Dosis"
      - "margin"
      - "padding"
      - "background-color"
      - "list-style-type"
      - "display"
      - "block"
      - "border"
